// PRODUCT LIST 3.js — Generated by Telegram UI Builder
// Generated at: 3/1/2026, 8:47:10 PM

async function sendPRODUCTLIST3(bot, chatId) {
  const message = `<b>📦 Product List</b>

28. Spotify Links
29. VPN Express
30. VPN HMA
31. VPN Surfshark
32. Viu
33. Voucher BOT
34. Wink
35. YouTube Premium
36. Zoom

📄 <b>Page 4/4</b>
💡<i> Enter a number to proceed.</i>`;

  // TODO: Replace with actual photo file path or URL
  const photo = 'photo.jpg';

  await bot.sendPhoto(chatId, photo, {
    caption: message,
    parse_mode: "HTML",
    reply_markup: {
      inline_keyboard: [
            [
                  {
                        "text": "← Previous",
                        "callback_data": "_previous"
                  }
            ]
      ]
    }
  });
}

module.exports = { sendPRODUCTLIST3 };
