// PRODUCT LIST 2.js — Generated by Telegram UI Builder
// Generated at: 3/1/2026, 8:47:10 PM

async function sendPRODUCTLIST2(bot, chatId) {
  const message = `<b>📦 Product List</b>

10. ChatGPT Sharing
11. Claude AI
12. GSuitexGOPAY
13. GSuitexPSC
14. Gemini AI
15. Gemini AI Link
16. Getcontact
17. Gmail Fresh
18. Google Drive

<b>📄 Page 2/4</b>
<i>💡 Enter a number to proceed.</i>`;

  // TODO: Replace with actual photo file path or URL
  const photo = 'photo.jpg';

  await bot.sendPhoto(chatId, photo, {
    caption: message,
    parse_mode: "HTML",
    reply_markup: {
      inline_keyboard: [
            [
                  {
                        "text": "Next →",
                        "callback_data": "next_"
                  },
                  {
                        "text": "← Previous",
                        "callback_data": "_previous"
                  }
            ]
      ]
    }
  });
}

module.exports = { sendPRODUCTLIST2 };
