// PRODUCT LIST.js — Generated by Telegram UI Builder
// Generated at: 01/03/2026, 20.08.57

async function sendPRODUCTLIST(bot, chatId) {
  const message = `<b>📦 Product List</b>

1. Alight Motion
2. Apple Music
3. Canva Basic
4. Canva Lifetime
5. Canva Pro
6. CapCut Basic
7. CapCut Famhead
8. Capcut Pro
9. ChatGPT Private

📄 <b>Page 1/4</b>
💡 <i>Enter a number to proceed.</i>`;

  // TODO: Replace with actual photo file path or URL
  const photo = 'photo.jpg';

  await bot.sendPhoto(chatId, photo, {
    caption: message,
    parse_mode: "HTML",
    reply_markup: {
      inline_keyboard: [
            [
                  {
                        "text": "Next →",
                        "callback_data": "next_"
                  }
            ]
      ]
    }
  });
}

module.exports = { sendPRODUCTLIST };
