// START.js — Generated by Telegram UI Builder
// Generated at: 01/03/2026, 20.08.57

async function sendSTART(bot, chatId) {
  const message = `Hello <b>riezkiiiii</b> 👋
Sunday, March 01, 2026 16:45:56

<b>User Information:</b>
ID: <code>1278400346</code>
Username: @riezkiiiii
Total Transactions: <b>Rp 216.561</b>
Balance: <b>Rp 0</b>

<b>Bot Statistics:</b>
Total Sold: 33.348.071 pcs
Total Users: 19.116

<b>Shortcuts:</b>
/start — Start
/stok — Stock
/saldo — Balance`;

  // TODO: Replace with actual photo file path or URL
  const photo = 'photo.jpg';

  await bot.sendPhoto(chatId, photo, {
    caption: message,
    parse_mode: "HTML"
  });
}

module.exports = { sendSTART };
